export default [
  {
    id: 'CL1',
    en_name: 'First class',
    pa_name: 'لومړي ټولګی',
    fa_name: 'صنف اول',
    fee: '50',
    en_duration: '6 Months',
    pa_duration: '6 میاشتې',
    fa_duration: '6 ماه ها',
    en_languages: 'English, Pashto, Dari',
    pa_languages: 'انګلیسي، پښتو، دری',
    fa_languages: 'انگلیسی، پښتو، دری',
    image_name: 'image_8.png',
    en_skill_level: 'Beginner',
    pa_skill_level: 'شروع',
    fa_skill_level: 'اپتدایه ',
    subjects: [
      {
        id: 'SU1',
        en_name: 'Noorani Qaida part one',
        pa_name: 'نوراني قاعده اوله برخه',
        fa_name: 'قاعده نورانی قسمت اول',
      },
      {
        id: 'SU2',
        en_name: 'Prayers / Masnonah prayers',
        pa_name: 'لمونځ / مسنوني دعاګاني',
        fa_name: 'نماز/ دعای مسنونه',
      },
      {
        id: 'SU3',
        en_name: 'Writing and Reading',
        pa_name: 'لیک او لوست ',
        fa_name: 'خواندن و نوشتن',
      },
    ],
  },
  {
    id: 'CL2',
    en_name: 'Second class',
    pa_name: 'دوهم ټولکی',
    fa_name: 'صنف دوم',
    fee: '50',
    en_duration: '6 Months',
    pa_duration: '6 میاشتې',
    fa_duration: '6 ماه ها',
    en_languages: 'English, Pashto, Dari',
    pa_languages: 'انګلیسي، پښتو، دری',
    fa_languages: 'انگلیسی، پښتو، دری',
    image_name: 'image_9.png',
    en_skill_level: 'Beginner',
    pa_skill_level: 'شروع',
    fa_skill_level: 'اپتدایه ',
    subjects: [
      {
        id: 'SU4',
        en_name: 'Noorani Noorani Qaida Part 2 / Reading 30th part of Quran',
        pa_name: 'نوراني قاعده دوهمه برخه / ناظره  ۳۰ سپاره',
        fa_name: 'قاعده نورانی قسمت دوم / ناظره  پاره ۳۰',
      },
      {
        id: 'SU5',
        en_name: 'Learning of prayer and ablotion',
        pa_name: 'د لمانځه او اوداسه زده کړه',
        fa_name: 'یادگیری نماز و وضو ',
      },
      {
        id: 'SU5',
        en_name: 'Writing and Reading',
        pa_name: 'لیک او لوست',
        fa_name: 'خواندن و نوشتن',
      },
    ],
  },
  {
    id: 'CL3',
    en_name: 'Third class',
    pa_name: 'دریم ټولکی',
    fa_name: 'صنف سوم',
    fee: '50',
    en_duration: '6 Months',
    pa_duration: '6 میاشتې',
    fa_duration: '6 ماه ها',
    en_languages: 'English, Pashto, Dari',
    pa_languages: 'انګلیسي، پښتو، دری',
    fa_languages: 'انگلیسی، پښتو، دری',
    image_name: 'image_10.png',
    en_skill_level: 'Intermediate',
    pa_skill_level: 'منځنی',
    fa_skill_level: 'متوسط',
    subjects: [
      {
        id: 'SU67',
        en_name: 'Reading of Quran (4 Parts) / Memorization of ten surahs',
        pa_name: 'د قرآن کریم ناظره ( ۴ سپارې ) / د لسو سورتونو حفظ',
        fa_name: 'ناظره قرآن کریم (4 پاره) / حفظ ۱۰ سوره',
      },
      {
        id: 'SU8',
        en_name: 'Taleemul Islam, First part',
        pa_name: 'تعلیم الاسلام اوله برخه',
        fa_name: 'تعلیم اسلام بخش اول',
      },
      {
        id: 'SU9',
        en_name: 'Islamic and historical stories',
        pa_name: 'اسلامي او تاریخي کیسې',
        fa_name: 'داستانهای اسلامی و تاریخی',
      },
      {
        id: 'SU10',
        en_name: 'Writing and Reading',
        pa_name: 'لیک او لوست',
        fa_name: 'خواندن و نوشتن',
      },
    ],
  },
  {
    id: 'CL4',
    en_name: 'Fourth class',
    pa_name: 'څلورم ټولکی',
    fa_name: 'صنف چهارم',
    fee: '50',
    en_duration: '6 Months',
    pa_duration: '6 میاشتې',
    fa_duration: '6 ماه ها',
    en_languages: 'English, Pashto, Dari',
    pa_languages: 'انګلیسي، پښتو، دری',
    fa_languages: 'انگلیسی، پښتو، دری',
    image_name: 'image_11.png',
    en_skill_level: 'Intermediate',
    pa_skill_level: 'منځنی',
    fa_skill_level: 'متوسط',
    subjects: [
      {
        id: 'SU11',
        en_name: 'Reading of Quran (7 Parts)',
        pa_name: 'ناظره ( ۷ سپارې)',
        fa_name: 'ناظره قرآن کریم (7 پاره)',
      },
      {
        id: 'SU12',
        en_name: 'Taleemul Islam Second part ',
        pa_name: 'تعلیم اسلام دوهمه برخه',
        fa_name: 'تعلیم و تربیت در اسلام، بخش دوم',
      },
      {
        id: 'SU13',
        en_name: 'Seeratul-Nabi',
        pa_name: 'سیرة النبي',
        fa_name: 'سیره النبی',
      },
      {
        id: 'SU14',
        en_name: 'Writing and Reading',
        pa_name: 'لیک او لوست',
        fa_name: 'خواندن و نوشتن',
      },
    ],
  },
  {
    id: 'CL5',
    en_name: 'Fifth class',
    pa_name: 'پنځم ټولکی',
    fa_name: 'صنف پنجم',
    fee: '50',
    en_duration: '6 Months',
    pa_duration: '6 میاشتې',
    fa_duration: '6 ماه ها',
    en_languages: 'English, Pashto, Dari',
    pa_languages: 'انګلیسي، پښتو، دری',
    fa_languages: 'انگلیسی، پښتو، دری',
    image_name: 'image_12.png',
    en_skill_level: 'Expert',
    pa_skill_level: 'ماهر',
    fa_skill_level: 'کارشناس',
    subjects: [
      {
        id: 'SU15',
        en_name: 'Reading of Quran (8 Parts)',
        pa_name: 'ناظره د ( ۸ سپارې)',
        fa_name: 'ناظره قرآن کریم (8 پاره)',
      },
      {
        id: 'SU16',
        en_name: 'Learning of Tajweed',
        pa_name: 'تجوید زده کړه',
        fa_name: 'آموزش تجوید',
      },
      {
        id: 'SU17',
        en_name: '20 hadiths',
        pa_name: '۲۰ حدیثونه',
        fa_name: '۲۰ حدیث',
      },
      {
        id: 'SU18',
        en_name: 'The life of the Ashab',
        pa_name: 'د اصحابو ژوند',
        fa_name: 'زندګی صحابه',
      },
      {
        id: 'SU19',
        en_name: 'Writing and Reading',
        pa_name: 'لیک او لوست',
        fa_name: 'خواندن و نوشتن',
      },
    ],
  },
  {
    id: 'CL6',
    en_name: 'Sixth class',
    pa_name: 'شپږم ټولکی',
    fa_name: 'صنف ششم',
    fee: '50',
    en_duration: '6 Months',
    pa_duration: '6 میاشتې',
    fa_duration: '6 ماه ها',
    en_languages: 'English, Pashto, Dari',
    pa_languages: 'انګلیسي، پښتو، دری',
    fa_languages: 'انگلیسی، پښتو، دری',
    image_name: 'image_13.png',
    en_skill_level: 'Expert',
    pa_skill_level: 'ماهر',
    fa_skill_level: 'کارشناس',
    subjects: [
      {
        id: 'SU20',
        en_name: 'Reading of Quran (10 Parts)',
        pa_name: 'ناظره (۱۰ سپارې)',
        fa_name: 'ناظره قرآن کریم (10 پاره)',
      },
      {
        id: 'SU21',
        en_name: 'Learning of Tajweed',
        pa_name: 'تجوید زده کړه',
        fa_name: 'آموزش تجوید',
      },
      {
        id: 'SU22',
        en_name: '20 hadiths',
        pa_name: '۲۰ حدیثونه',
        fa_name: '۲۰ احادیث',
      },
      {
        id: 'SU23',
        en_name: 'The life of the Ashab',
        pa_name: 'د صحابیاتو ژوند',
        fa_name: 'زندگی صحابه',
      },
      {
        id: 'SU24',
        en_name: 'Writing and Reading',
        pa_name: 'لیک او لوست',
        fa_name: 'خواندن و نوشتن',
      },
    ],
  },
]
