export default [
  {
    id: 'CO1',
    en_name: 'Fahmul Quran Kareem with Noorani Qaida',
    pa_name: 'قران کریم زده کړه له نوراني قاعدې سره',
    fa_name: 'قران کریم با قاعده نوارني',
    fee: '50',
    en_duration: '6 Months',
    pa_duration: '6 میاشتې',
    fa_duration: '6 ماه ها',
    en_languages: 'English, Pashto, Dari',
    pa_languages: 'انګلیسي، پښتو، دری',
    fa_languages: 'انگلیسی، پښتو، دری',
    en_skill_level: 'Beginner',
    pa_skill_level: 'شروع',
    fa_skill_level: 'اپتدایه ',
    en_discription:
      'In this course, students will learn to read the Holy Quran for the first time by using the Noorani Qaida',
    pa_discription:
      'دا کورس کي به زده کوونکي د لومړي ځل لـه پاره د قرآن کریم لوستل د نوراني قاعدې په واسطه سره زده کړي',
    fa_discription:
      'در این دوره دانش آموزان برای اولین بار با استفاده از قاعده نورانی قرائت قرآن کریم را فرا می گیرند.',
    image_name: 'image_1.png',
  },
  {
    id: 'CO2',
    en_name: 'Tajweed Learning',
    pa_name: 'تجوید زده کړه',
    fa_name: 'آموزش تجوید',
    fee: '50',
    en_duration: '6 Months',
    pa_duration: '6 میاشتې',
    fa_duration: '6 ماه ها',
    en_languages: 'English, Pashto, Dari',
    pa_languages: 'انګلیسي، پښتو، دری',
    fa_languages: 'انگلیسی، پښتو، دری',
    en_skill_level: 'Beginner',
    pa_skill_level: 'شروع',
    fa_skill_level: 'اپتدایه ',
    en_discription:
      "In this course, students will be able to identify the Arabic letters with their adjectives so that they can recite the Holy Qur'an with better Tajweed.",
    pa_discription:
      'دا کورس کي به زده کوونکي وکولای سي چي د عربي حروفو مخرجونه سره د خپلو صفتونو وپېژني ترڅو قــــرآن کریم به په غـــــوره تجوید سره تلاوت کړي',
    fa_discription:
      'در این دوره دانش آموزان قادر خواهند بود حروف عربی را با صفت خود شناسایی کنند تا بتوانند قرآن کریم را با تجوید بهتری تلاوت کنند.',
    image_name: 'image_2.png',
  },
  {
    id: 'CO3',
    en_name: 'Islamic Fundamentals',
    pa_name: 'اسلامي اساسات',
    fa_name: 'اساسات اسلام',
    fee: '50',
    en_duration: '6 Months',
    pa_duration: '6 میاشتې',
    fa_duration: '6 ماه ها',
    en_languages: 'English, Pashto, Dari',
    pa_languages: 'انګلیسي، پښتو، دری',
    fa_languages: 'انگلیسی، پښتو، دری',
    en_skill_level: 'Beginner',
    pa_skill_level: 'شروع',
    fa_skill_level: 'اپتدایه ',
    en_discription:
      'In this course, students can learn about the basics of Islam, such as the basic Aqidah, the five pillars of Islam, and the knowledge of hadith.',
    pa_discription:
      'دا کورس کي زده کوونکو کولای د اسلام په اساساتو لکه بنسټیز عقیده، د اســـلام پنځه رکنونه، او د حدیث د علم په اړه پوه سي',
    fa_discription:
      'در این دوره دانشجویان می توانند با مبانی اسلام مانند اعتقادات اساسی، ارکان پنج گانه اسلام و دانش حدیث آشنا شوند.',
    image_name: 'image_3.png',
  },
  {
    id: 'CO4',
    en_name: 'Pashto Learning',
    pa_name: 'پښتو زده کړه',
    fa_name: 'آموزش پښتو',
    fee: '50',
    en_duration: '6 Months',
    pa_duration: '6 میاشتې',
    fa_duration: '6 ماه ها',
    en_languages: 'English, Pashto, Dari',
    pa_languages: 'انګلیسي، پښتو، دری',
    fa_languages: 'انگلیسی، پښتو، دری',
    en_skill_level: 'Beginner',
    pa_skill_level: 'شروع',
    fa_skill_level: 'اپتدایه ',
    en_discription:
      'Here you will learn the basics of the Pashto language, and you will can writhe and read by this language',
    pa_discription:
      'دلته به تاسو د پښتو ژبي اساسات زده کړي او تاسو به کولای سئ چي په دې ژبه باندي لیکل او لوستل وکړئ!',
    fa_discription:
      'در اینجا شما اصول اولیه زبان پښتو را یاد می گیرید و می توانید در این زبان بخوانید و بنویسید!',
    image_name: 'image_4.png',
  },
  {
    id: 'CO5',
    en_name: 'Dari Learning',
    pa_name: 'دری زده کړه',
    fa_name: 'آموزش دری',
    fee: '50',
    en_duration: '6 Months',
    pa_duration: '6 میاشتې',
    fa_duration: '6 ماه ها',
    en_languages: 'English, Pashto, Dari',
    pa_languages: 'انګلیسي، پښتو، دری',
    fa_languages: 'انگلیسی، پښتو، دری',
    en_skill_level: 'Beginner',
    pa_skill_level: 'شروع',
    fa_skill_level: 'اپتدایه ',
    en_discription:
      'Here you will learn the basics of the Dari language, and you will can writhe and read by this language.',
    pa_discription:
      'دلته به تاسو د دری ژبي اساسات زده کړي او تاسو به کولای سئ چي په دې ژبه باندي لیکل او لوستل وکړئ! ',
    fa_discription:
      'در اینجا شما اصول اولیه زبان دری را یاد می گیرید و می توانید در این زبان بخوانید و بنویسید!',
    image_name: 'image_5.png',
  },
  {
    id: 'CO6',
    en_name: 'Arabi Learning',
    pa_name: 'عربي زده کړه',
    fa_name: 'آموزش عربی',
    fee: '50',
    en_duration: '6 Months',
    pa_duration: '6 میاشتې',
    fa_duration: '6 ماه ها',
    en_languages: 'English, Pashto, Dari',
    pa_languages: 'انګلیسي، پښتو، دری',
    fa_languages: 'انگلیسی، پښتو، دری',
    en_skill_level: 'Beginner',
    pa_skill_level: 'شروع',
    fa_skill_level: 'اپتدایه ',
    en_discription:
      'Here you will learn the basics of the Arabi language, and you will can writhe and read by this language',
    pa_discription:
      'دلته به تاسو د عربی ژبي اساسات زده کړي او تاسو به کولای سئ چي په دې ژبه باندي لیکل او لوستل وکړئ!',
    fa_discription:
      'در اینجا شما اصول اولیه زبان عربی را یاد می گیرید و می توانید در این زبان بخوانید و بنویسید!',
    image_name: 'image_6.png',
  },
  {
    id: 'CO7',
    en_name: 'English Learning',
    pa_name: 'انګلیسي زده کړه',
    fa_name: 'آموزش انګیسي',
    fee: '50',
    en_duration: '6 Months',
    pa_duration: '6 میاشتې',
    fa_duration: '6 ماه ها',
    en_languages: 'English, Pashto, Dari',
    pa_languages: 'انګلیسي، پښتو، دری',
    fa_languages: 'انگلیسی، پښتو، دری',
    en_skill_level: 'Beginner',
    pa_skill_level: 'شروع',
    fa_skill_level: 'اپتدایه ',
    en_discription:
      'Here you will learn the basics of the English language, and you will can writhe and read by this language',
    pa_discription:
      'دلته به تاسو د انګلیسی ژبي اساسات زده کړي او تاسو به کولای سئ چي په دې ژبه باندي لیکل او لوستل وکړئ!',
    fa_discription:
      'در اینجا شما اصول اولیه زبان انگلیسی را یاد می گیرید و می توانید در این زبان بخوانید و بنویسید!',
    image_name: 'image_7.png',
  },
]
